# Data collection and cleaning

This is where we collect and clean our dataset.

In [73]:
import pandas as pd
import numpy as np

In [74]:
users = pd.read_csv("data/users.csv")

top_artists = pd.read_csv("data/user_top_artists.csv")
top_tracks = pd.read_csv("data/user_top_tracks.csv")
top_albums = pd.read_csv("data/user_top_albums.csv")

In [75]:
print("Users table\n")
print(users.head())

print("\nUsers top artists' table\n")
print(top_artists.head())

print("\nUsers top tracks' table\n")
print(top_tracks.head())

print("\nUsers top albums' table\n")
print(top_albums.head())

Users table

   user_id         country  total_scrobbles
0        1   United States           204985
1        2          France           211013
2        3           Spain           244871
3        4          Israel            69401
4        5  United Kingdom            95449

Users top artists' table

   user_id  rank       artist_name  playcount  \
0        1     1   Crystal Castles       1034
1        1     2         Radiohead        972
2        1     3          Ladytron        831
3        1     4  Ghostface Killah        801
4        1     5             UNKLE        722

                                   mbid
0  b1570544-93ab-4b2b-8398-131735394202
1  a74b1b7f-71a5-4011-9441-d0b5e4122711
2  b45335d1-5219-4262-a44d-936aa36eeaed
3  3b39abeb-0064-4eed-9ddd-ee47a45c54cb
4  6648391e-7890-4f6c-b939-976f215195d3

Users top tracks' table

   user_id  rank               track_name          artist_name  playcount  \
0        1     1                Ice Cream  New Young Pony Club         54
1        1     2  Hiding On The Staircase  New Young Pony Club         51
2        1     3                  Descend  New Young Pony Club         49
3        1     4                  Air War      Crystal Castles         48
4        1     5                Get Lucky  New Young Pony Club         48

                                   mbid
0  417a3d0b-0291-4e08-b167-50971dbdae36
1  f6ac2fd2-b33b-48ff-a094-537cf530cf20
2  33434fd1-79a1-3882-bb31-fbd430815a93
3  06d3fea3-e806-35ed-9562-aa396a97de14
4  ab351b25-7126-3792-9b0d-ce44fd0c0462

Users top albums' table

   user_id  rank               album_name       artist_name  playcount  \
0        1     1                  Visions            Grimes        243
1        1     2  Only Built 4 Cuban Linx           Raekwon        240
2        1     3    Tales From the Pantry  Lederhosen Lucil        204
3        1     4          Crystal Castles   Crystal Castles        200
4        1     5                Klanguage         Klanguage        184

                                   mbid
0  0136a543-33fa-4b80-a8ca-4a6094db3b71
1  c49af812-cb43-45ca-81e6-b81b7c287624
2  1f195540-653f-4db4-bb74-e7d215de9bae
3  101f993f-d5e1-3f14-b40b-71850f1f435a
4  e82aa7a2-9d34-431f-9199-c8eba2df0261

In [76]:
users = users[users["total_scrobbles"] > 150000].copy()
users = users[users["country"] == "United States"]
top_user_ids = set(users["user_id"])

top_artists = top_artists[top_artists["user_id"].isin(top_user_ids)]
top_tracks = top_tracks[top_tracks["user_id"].isin(top_user_ids)]
top_albums = top_albums[top_albums["user_id"].isin(top_user_ids)]

In [77]:
len(users)

14411

In [78]:
users = users.drop_duplicates(subset="user_id")
top_artists = top_artists.drop_duplicates(subset=["user_id", "artist_name"])
top_tracks = top_tracks.drop_duplicates(subset=["user_id", "track_name"])
top_albums = top_albums.drop_duplicates(subset=["user_id", "album_name"])

In [79]:
def clean_text(text):
    if pd.isna(text):
        return ""
    return text.strip().lower()

for df, cols in [
    (top_artists, ["artist_name"]),
    (top_tracks, ["artist_name", "track_name"]),
    (top_albums, ["artist_name", "album_name"])
]:
    for col in cols:
        df[col] = df[col].apply(clean_text)

# Replace empty mbid with NaN
for df in [top_artists, top_tracks, top_albums]:
    df["mbid"] = df["mbid"].replace("", pd.NA)

In [80]:
# Normalize playcount per user (so they sum to 1)
def normalize_playcount(df, group_col="user_id"):
    df["playcount_norm"] = df["playcount"] / df.groupby(group_col)["playcount"].transform("sum")
    return df

top_artists = normalize_playcount(top_artists)
top_tracks = normalize_playcount(top_tracks)
top_albums = normalize_playcount(top_albums)

# Merge with users table
top_artists = top_artists.merge(users, on="user_id", how="left")
top_tracks = top_tracks.merge(users, on="user_id", how="left")
top_albums = top_albums.merge(users, on="user_id", how="left")

In [81]:
spotify = pd.read_csv("data/spotify_dataset.csv")

spotify["song"] = spotify["song"].apply(clean_text)
spotify["Artist(s)"] = spotify["Artist(s)"].apply(clean_text)

In [82]:
spotify

,Artist(s),song,text,Length,emotion,Genre,Album,Release Date,Key,Tempo,...,Good for Morning Routine,Similar Artist 1,Similar Song 1,Similarity Score 1,Similar Artist 2,Similar Song 2,Similarity Score 2,Similar Artist 3,Similar Song 3,Similarity Score 3
0,!!!,even when the waters cold,Friends told her she was better off at the bot...,03:47,sadness,hip hop,Thr!!!er,29th April 2013,D min,105,...,0,Corey Smith,If I Could Do It Again,0.986061,Toby Keith,Drinks After Work,0.983719,Space,Neighbourhood,0.983236
1,!!!,one girl / one boy,"Well I heard it, playing soft From a drunken b...",04:03,sadness,hip hop,Thr!!!er,29th April 2013,A# min,117,...,0,Hiroyuki Sawano,BRE@TH//LESS,0.995409,When In Rome,Heaven Knows,0.990905,Justice Crew,Everybody,0.984483
2,!!!,pardon my freedom,"Oh my god, did I just say that out loud? Shoul...",05:51,joy,hip hop,Louden Up Now,8th June 2004,A Maj,121,...,0,Ricky Dillard,More Abundantly Medley Live,0.993176,Juliet,Avalon,0.965147,The Jacksons,Lovely One,0.956752
3,!!!,ooo,[Verse 1] Remember when I called you on the te...,03:44,joy,hip hop,As If,16th October 2015,A min,122,...,0,Eric Clapton,Man Overboard,0.992749,Roxette,Don't Believe In Accidents,0.991494,Tiwa Savage,My Darlin,0.990381
4,!!!,freedom 15,[Verse 1] Calling me like I got something to s...,06:00,joy,hip hop,As If,16th October 2015,F min,123,...,0,Cibo Matto,Lint Of Love,0.981610,Barrington Levy,Better Than Gold,0.981524,Freestyle,Its Automatic,0.981415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551438,박혜진 park hye jin,can you,Can you be my (Can you be my) Can you be my (C...,03:39,joy,house,Can you (Galcher Lustwerk Remix),14th October 2020,B min,140,...,0,LXST CXNTURY,NEVER EXISTED,0.946429,"Occvlt,StoneDogg",ALIZAY,0.926155,Peaches,Light in Places,0.923749
551439,심형진 hyungjin sim,lim han byul lee hyuk - prayer english transl...,[Verse] I gave you my everything But I see I c...,08:47,joy,metalcore,비 준비하시니 Psalm_147,19th April 2022,G# Maj,128,...,0,Kari Jobe,No Fear Live,0.991961,"The Belonging Co,Kari Jobe",Closer To Your Heart,0.990956,Saintseneca,Pillar of Na,0.990385
551440,우정하,memories smiling tears remix,"[Tasha] Hell on earth, watching ...",03:53,sadness,hip hop,MEMORY,30th August 2023,G# min,75,...,0,Manic Street Preachers,People Give In,0.982809,Vinyl Theatre,Gold,0.980835,Unspoken,Life in the Death of Me,0.980171
551441,제노,come back to me,[Verse] Gifts and flowers lay upon the lid Of ...,03:12,sadness,hip hop,2008 to me again,3rd June 2008,E Maj,126,...,0,Bonnie Raitt,I Can't Help Myself,0.983805,J. Roddy Walston & The Business,Bad Habits,0.982425,Idina Menzel,Damsel In Distress,0.975935
551442,코케,i wanna be with you,I wanna b with you I wanna b with you baby Yea...,03:32,love,hip hop,I Wanna Be With You : Originally Performed By ...,4th November 2020,D Maj,100,...,0,Ameritz - Karaoke,Roxanne 97 Puff Daddy Remix,0.987132,Ameritz - Karaoke,Roxanne,0.987132,ProSource Karaoke,Get Back Single Version,0.984674

In [83]:
top_tracks

,user_id,rank,track_name,artist_name,playcount,mbid,playcount_norm,country,total_scrobbles
0,1,1,ice cream,new young pony club,54,417a3d0b-0291-4e08-b167-50971dbdae36,0.034177,United States,204985
1,1,2,hiding on the staircase,new young pony club,51,f6ac2fd2-b33b-48ff-a094-537cf530cf20,0.032278,United States,204985
2,1,3,descend,new young pony club,49,33434fd1-79a1-3882-bb31-fbd430815a93,0.031013,United States,204985
3,1,4,air war,crystal castles,48,06d3fea3-e806-35ed-9562-aa396a97de14,0.030380,United States,204985
4,1,5,get lucky,new young pony club,48,ab351b25-7126-3792-9b0d-ce44fd0c0462,0.030380,United States,204985
...,...,...,...,...,...,...,...,...,...
719097,479469,46,marshland canopy,milieu,48,NaN,0.017461,United States,377013
719098,479469,47,mmx 6b,milieu,48,NaN,0.017461,United States,377013
719099,479469,48,path (live version),milieu,48,NaN,0.017461,United States,377013
719100,479469,49,rain metre,milieu,48,a93c0566-1f6b-3623-a54c-f0fca49ce85b,0.017461,United States,377013
719101,479469,50,schoolbells,milieu,48,536a164c-641b-3490-9411-e66b80cc71db,0.017461,United States,377013

In [84]:
merged = top_tracks.merge(
    spotify,
    left_on=["track_name", "artist_name"],
    right_on=["song", "Artist(s)"],
    how="inner"
)

In [85]:
merged

,user_id,rank,track_name,artist_name,playcount,mbid,playcount_norm,country,total_scrobbles,Artist(s),...,Good for Morning Routine,Similar Artist 1,Similar Song 1,Similarity Score 1,Similar Artist 2,Similar Song 2,Similarity Score 2,Similar Artist 3,Similar Song 3,Similarity Score 3
0,1,1,ice cream,new young pony club,54,417a3d0b-0291-4e08-b167-50971dbdae36,0.034177,United States,204985,new young pony club,...,0,Alton Ellis,What Does it Take,0.987306,"""Weird Al"" Yankovic",Word Crimes,0.985525,the bird and the bee,I Cant Go for That,0.980872
1,1,4,air war,crystal castles,48,06d3fea3-e806-35ed-9562-aa396a97de14,0.030380,United States,204985,crystal castles,...,0,"DeepDelic,Raphael Siqueira",Livin,0.987740,George Michael,Killer/Papa Was a Rollin Stone,0.976959,"Christina Aguilera,Lil' Kim,Mýa,P!nk",Climb Every Mountain,0.975044
2,1,7,love and caring,crystal castles,45,1f269fe8-d6a6-3510-bbcc-70745bf72e8b,0.028481,United States,204985,crystal castles,...,0,NOAHFINNCE,STUPID,0.953349,"Ashnikko,Kodie Shane",Im So Gone,0.952749,"D. Savage,Matt OX,K Suave",Bring Me Down,0.939264
3,1,8,the get go,new young pony club,43,85919992-5ff5-3047-9e64-734063c69af8,0.027215,United States,204985,new young pony club,...,0,Bob Dylan,Neighborhood Bully,0.988796,A Fine Frenzy,Blow Away,0.987982,The Prize Fighter Inferno,Elm Street Lover Boy,0.987086
4,1,10,courtship dating,crystal castles,39,201509e4-b281-3404-9799-f013868e722f,0.024684,United States,204985,crystal castles,...,1,Vintage Culture,Bros,0.978891,Prince,Computer Blue,0.966752,Nolan Porter,If I Could Only Be Sure,0.965075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346765,479339,29,the art of peer pressure,kendrick lamar,189,fd83178d-c064-4689-9c09-bef8f1c4cad9,0.017229,United States,344702,kendrick lamar,...,0,Fiona Apple,Relay,0.964223,Makaveli,Makaveli 95,0.956796,Drake,City Is Mine,0.952395
346766,479339,43,haunted,laura les,177,b9eddf3f-4db8-4945-85da-04a0bef6edfc,0.016135,United States,344702,laura les,...,0,Stellar,Masquerade,0.971590,The Score,Fighter,0.970723,Simple Plan,Whats New Scooby-Doo?,0.966923
346767,479339,44,the less i know the better,tame impala,176,78be434c-0908-458f-9693-f16cdebb68ef,0.016044,United States,344702,tame impala,...,0,"Post Malone,Morgan Wallen",Socialite,0.975689,"Post Malone,Morgan Wallen",About a Girl,0.975689,"Post Malone,Morgan Wallen",Ric Flair,0.975689
346768,479339,46,magnolia,playboi carti,170,2fa630fd-4eaa-4db1-ab9f-ca8fb4027322,0.015497,United States,344702,playboi carti,...,0,Playboi Carti,In My Car,1.000000,Playboi Carti,Classroom,1.000000,"Lil Mabu,DUSTY LOCANE",BEST FRIEND,0.976478
346769,479339,47,ferrari,alice gas,169,9affbdb5-cd5f-4630-9ec4-1337644054fc,0.015406,United States,344702,alice gas,...,0,Guns N' Roses,Shadow of Your Love,0.984826,Guns N' Roses,Shadow Of Your Love,0.984821,"Scandroid,The Forgotten",Shout,0.969598

In [86]:

feature_cols = merged.select_dtypes(include=["int64", "float64"]).columns
feature_cols = feature_cols.drop([
    "user_id", "rank",
    "playcount", "playcount_norm",
    "total_scrobbles_x", "total_scrobbles_y", "total_scrobbles"
], errors="ignore")

feature_cols

Index(['Tempo', 'Popularity', 'Energy', 'Danceability', 'Positiveness',
       'Speechiness', 'Liveness', 'Acousticness', 'Instrumentalness',
       'Good for Party', 'Good for Work/Study',
       'Good for Relaxation/Meditation', 'Good for Exercise',
       'Good for Running', 'Good for Yoga/Stretching', 'Good for Driving',
       'Good for Social Gatherings', 'Good for Morning Routine',
       'Similarity Score 1', 'Similarity Score 2', 'Similarity Score 3'],
      dtype='object')

In [87]:
user_features = merged.groupby("user_id")[feature_cols].mean()
user_features

,Tempo,Popularity,Energy,Danceability,Positiveness,Speechiness,Liveness,Acousticness,Instrumentalness,Good for Party,...,Good for Relaxation/Meditation,Good for Exercise,Good for Running,Good for Yoga/Stretching,Good for Driving,Good for Social Gatherings,Good for Morning Routine,Similarity Score 1,Similarity Score 2,Similarity Score 3
user_id,,,,,,,,,,,,,,,,,,,,,
1,126.150000,47.600000,62.400000,65.550000,52.700000,6.400000,17.550000,16.000000,16.750000,0.300000,...,0.050000,0.450000,0.000000,0.050000,0.100000,0.200000,0.300000,0.981796,0.974978,0.972527
30,121.666667,48.000000,68.969697,54.303030,53.727273,7.515152,17.636364,19.303030,14.000000,0.090909,...,0.000000,0.121212,0.000000,0.000000,0.060606,0.000000,0.030303,0.979531,0.974126,0.971424
97,133.878788,45.303030,78.333333,43.666667,45.424242,6.909091,21.787879,10.636364,3.121212,0.000000,...,0.000000,0.090909,0.060606,0.000000,0.000000,0.000000,0.000000,0.985925,0.979452,0.975656
151,128.250000,48.250000,53.022727,47.022727,43.727273,4.704545,15.318182,39.522727,27.500000,0.090909,...,0.022727,0.136364,0.022727,0.022727,0.045455,0.045455,0.045455,0.984632,0.975811,0.972205
209,144.260870,51.130435,86.434783,45.565217,58.956522,10.913043,26.869565,7.782609,4.304348,0.173913,...,0.000000,0.217391,0.130435,0.000000,0.000000,0.000000,0.043478,0.985279,0.978542,0.975669
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478969,129.909091,60.000000,66.454545,71.727273,46.363636,18.545455,18.272727,4.363636,1.181818,0.363636,...,0.000000,0.363636,0.090909,0.000000,0.000000,0.000000,0.090909,0.989203,0.986336,0.982065
479269,118.545455,42.318182,63.136364,45.772727,38.250000,5.886364,15.250000,28.500000,15.022727,0.000000,...,0.022727,0.045455,0.022727,0.000000,0.022727,0.000000,0.000000,0.984453,0.979415,0.977142
479275,119.575758,59.575758,73.454545,56.696970,52.151515,4.696970,18.575758,13.060606,0.000000,0.424242,...,0.000000,0.424242,0.030303,0.000000,0.000000,0.030303,0.030303,0.991664,0.988612,0.986518
479294,129.400000,46.900000,63.450000,44.100000,26.150000,4.800000,25.750000,27.000000,10.450000,0.050000,...,0.100000,0.050000,0.000000,0.050000,0.000000,0.000000,0.050000,0.986074,0.981135,0.978405
479339,119.181818,67.000000,70.090909,61.818182,44.090909,21.000000,20.454545,14.727273,1.272727,0.181818,...,0.000000,0.181818,0.090909,0.000000,0.000000,0.000000,0.000000,0.985342,0.980046,0.972604

In [88]:
user_features.to_csv("data/user_features.csv")